### ISSUE TITLE
Dependency convergence error

### ISSUE THREAD

**Issue by RafikTSG** [facebookexperimental/jcommon#48]
During building with Maven:

[WARNING]
Dependency convergence error for joda-time:joda-time:2.9.4 paths to dependency are:
  +-com.facebook.jcommon:util:0.1.29
    +-joda-time:joda-time:2.9.4
and
  +-com.facebook.jcommon:util:0.1.29
    +-com.fasterxml.jackson.datatype:jackson-datatype-joda:2.7.4
      +-joda-time:joda-time:2.4

**Comment by rash67** [comment]
what exact command are you running to produce this warning?

**Comment by RafikTSG** [comment]
I wanted to use some tools from:
		<dependency>
			<groupId>com.facebook.jcommon</groupId>
			<artifactId>util</artifactId>
			<version>0.1.29</version>
		</dependency>

Above warning was produced by just calling:
mvn -U package

Do you mean you don't have such warning?

**Comment by rash67** [comment]
odd, I'm not seeing it.

does it fail for you? or is it just a warning?
what version of maven is it?

i don't think this is an issue as we force the higher version of jodatime (2.9.4) in the dependencyManagement section. This usually should stop the warning (that or an exclusion)

**Comment by RafikTSG** [comment]
I'm using "Apache Maven 3.3.9".

**Comment by srash** [comment]
Sorry, i couldn’t reproduce this. can you give me more information about the exact sequence of steps to reproduce?

eg
1. checkout
2 run mvn install from root dir
