### ISSUE TITLE
Link error for Media:Java--CodingStandards--IntelliJIdea11-settings.jar

### ISSUE THREAD

**Issue by ee08b397** [facebookexperimental/jcommon#52]
The link in wiki under https://github.com/facebook/jcommon/wiki/Coding-Standards#settings 
```
Media:Java--CodingStandards--IntelliJIdea11-settings.jar
```
is pointing to `https://github.com/facebook/jcommon/wiki` which is not a file. Looking forward to trying it out.

**Comment by jesboat** [comment]
we killed the wiki
